# Configuration for RL mode
# This mode trains and evaluates a PPO agent on the POFJSP benchmark

enabled: true

# RL Agent parameters
agent:
  learning_rate: 3.0e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  device: "auto"  # "auto", "cpu", or "cuda"
  seed: 42

# Training parameters
training:
  total_timesteps: 1000000
  n_envs: 4
  save_models: true
  models_dir: "outputs/rl_models"
  
# Evaluation parameters
evaluation:
  enabled: true
  n_eval_episodes: 5
  deterministic: true

# Visualization
visualization:
  enabled: true
  save_dir: "figures/rl_results" 